pub struct PlanetData {
    pub mass: f32,                // 10^24kg
    pub diameter: f32,            // km
    pub density: f32,             // kg/m^3
    pub gravity: f32,             // m/s^2
    pub escape_velocity: f32,     // km/s
    pub rotation_period: f32,     // hours
    pub distance_from_sun: f32,   // 10^6 km
    pub length_of_day: f32,       // Hours
    pub pharihelion: f32,         // 10^6 km
    pub aphelion: f32,            // 10^6 km
    pub orbital_period: f32,      //days
    pub orbital_velocity: f32,    //km/s
    pub orbital_inclination: f32, // degrees
    pub orbital_eccentricity: f32,
    pub obliquity_to_orbit: f32, // degrees
    pub mean_temprature: f32,    // Celcius
    pub surface_pressure: f32,   // bars
    pub number_of_moons: isize,
    pub ring_system: bool,
    pub global_magnetic_field: bool,
}

impl PlanetData {
    pub const SUN: PlanetData = PlanetData {
        mass: 19884700.,
        diameter: 1392700.0,
        density: 0.00141,
        gravity: 274.,
        escape_velocity: 615.,
        rotation_period: 24.0 * 27.0, // About 27 days
        length_of_day: 0.0,
        distance_from_sun: 0.,
        pharihelion: 0.,
        aphelion: 0.,
        orbital_period: 0.,
        orbital_velocity: 0.,
        orbital_inclination: 0.,
        orbital_eccentricity: 0.,
        obliquity_to_orbit: 0.0,
        mean_temprature: 5.500,
        surface_pressure: 0.0,
        number_of_moons: 0,
        ring_system: false,
        global_magnetic_field: true,
    };

    pub const MERCURY: PlanetData = PlanetData {
        mass: 0.330,
        diameter: 4879.0,
        density: 5429.0,
        gravity: 3.7,
        escape_velocity: 4.3,
        rotation_period: 1407.6,
        length_of_day: 4222.6,
        distance_from_sun: 57.9,
        pharihelion: 46.0,
        aphelion: 69.8,
        orbital_period: 88.0,
        orbital_velocity: 47.4,
        orbital_inclination: 7.0,
        orbital_eccentricity: 0.206,
        obliquity_to_orbit: 0.034,
        mean_temprature: 167.0,
        surface_pressure: 0.0,
        number_of_moons: 0,
        ring_system: false,
        global_magnetic_field: true,
    };
    pub const VENUS: PlanetData = PlanetData {
        mass: 4.87,
        diameter: 12104.0,
        density: 5243.,
        gravity: 8.9,
        escape_velocity: 10.4,
        rotation_period: -5832.5,
        length_of_day: 2802.0,
        distance_from_sun: 108.2,
        pharihelion: 107.5,
        aphelion: 108.9,
        orbital_period: 224.7,
        orbital_velocity: 35.0,
        orbital_inclination: 3.4,
        orbital_eccentricity: 0.007,
        obliquity_to_orbit: 177.4,
        mean_temprature: 464.,
        surface_pressure: 92.,
        number_of_moons: 0,
        ring_system: false,
        global_magnetic_field: false,
    };

    pub const EARTH: PlanetData = PlanetData {
        mass: 5.97,
        diameter: 12756.0,
        density: 5514.,
        gravity: 9.8,
        escape_velocity: 11.2,
        rotation_period: 23.9,
        length_of_day: 24.0,
        distance_from_sun: 149.6,
        pharihelion: 147.1,
        aphelion: 152.1,
        orbital_period: 365.2,
        orbital_velocity: 29.8,
        orbital_inclination: 0.0,
        orbital_eccentricity: 0.017,
        obliquity_to_orbit: 23.4,
        mean_temprature: 15.,
        surface_pressure: 1.,
        number_of_moons: 1,
        ring_system: false,
        global_magnetic_field: true,
    };
    pub const MOON: PlanetData = PlanetData {
        mass: 0.073,
        diameter: 3475.,
        density: 3340.,
        gravity: 1.6,
        escape_velocity: 2.4,
        rotation_period: 655.7,
        length_of_day: 708.7,
        distance_from_sun: 0.384,
        pharihelion: 0.363,
        aphelion: 0.406,
        orbital_period: 27.3,
        orbital_velocity: 1.0,
        orbital_inclination: 5.1,
        orbital_eccentricity: 0.055,
        obliquity_to_orbit: 6.7,
        mean_temprature: -20.,
        surface_pressure: 0.,
        number_of_moons: 0,
        ring_system: false,
        global_magnetic_field: false,
    };
    pub const MARS: PlanetData = PlanetData {
        mass: 0.642,
        diameter: 6792.,
        density: 3934.,
        gravity: 3.7,
        escape_velocity: 5.0,
        rotation_period: 24.6,
        length_of_day: 24.7,
        distance_from_sun: 228.0,
        pharihelion: 206.7,
        aphelion: 249.3,
        orbital_period: 687.0,
        orbital_velocity: 24.1,
        orbital_inclination: 1.8,
        orbital_eccentricity: 0.094,
        obliquity_to_orbit: 25.2,
        mean_temprature: -65.,
        surface_pressure: 0.01,
        number_of_moons: 2,
        ring_system: false,
        global_magnetic_field: false,
    };
    pub const JUPITER: PlanetData = PlanetData {
        mass: 1898.,
        diameter: 142.984,
        density: 1326.,
        gravity: 23.1,
        escape_velocity: 59.5,
        rotation_period: 9.9,
        length_of_day: 9.9,
        distance_from_sun: 778.5,
        pharihelion: 740.6,
        aphelion: 816.4,
        orbital_period: 4331.,
        orbital_velocity: 13.1,
        orbital_inclination: 1.3,
        orbital_eccentricity: 0.049,
        obliquity_to_orbit: 3.1,
        mean_temprature: -110.,
        surface_pressure: 0.,
        number_of_moons: 79,
        ring_system: true,
        global_magnetic_field: true,
    };

    pub const SATURN: PlanetData = PlanetData {
        mass: 568.,
        diameter: 120.536,
        density: 687.,
        gravity: 9.0,
        escape_velocity: 35.5,
        rotation_period: 10.7,
        length_of_day: 10.7,
        distance_from_sun: 1432.0,
        pharihelion: 1357.6,
        aphelion: 1506.5,
        orbital_period: 10.747,
        orbital_velocity: 9.7,
        orbital_inclination: 2.5,
        orbital_eccentricity: 0.052,
        obliquity_to_orbit: 26.7,
        mean_temprature: -140.,
        surface_pressure: 0.,
        number_of_moons: 82,
        ring_system: true,
        global_magnetic_field: true,
    };

    pub const URANUS: PlanetData = PlanetData {
        mass: 86.8,
        diameter: 51.118,
        density: 1270.,
        gravity: 8.7,
        escape_velocity: 21.3,
        rotation_period: -17.2,
        length_of_day: 17.2,
        distance_from_sun: 2867.0,
        pharihelion: 2732.7,
        aphelion: 3001.4,
        orbital_period: 30.589,
        orbital_velocity: 6.8,
        orbital_inclination: 0.8,
        orbital_eccentricity: 0.047,
        obliquity_to_orbit: 97.8,
        mean_temprature: -195.,
        surface_pressure: 0.,
        number_of_moons: 27,
        ring_system: true,
        global_magnetic_field: true,
    };

    pub const NEPTUNE: PlanetData = PlanetData {
        mass: 102.,
        diameter: 49.528,
        density: 1638.,
        gravity: 11.0,
        escape_velocity: 23.5,
        rotation_period: 16.1,
        length_of_day: 16.1,
        distance_from_sun: 4515.0,
        pharihelion: 4471.1,
        aphelion: 4558.9,
        orbital_period: 59.800,
        orbital_velocity: 5.4,
        orbital_inclination: 1.8,
        orbital_eccentricity: 0.010,
        obliquity_to_orbit: 28.3,
        mean_temprature: -200.,
        surface_pressure: 0.,
        number_of_moons: 14,
        ring_system: true,
        global_magnetic_field: true,
    };

    pub const PLUTO: PlanetData = PlanetData {
        mass: 0.0130,
        diameter: 2376.,
        density: 1850.,
        gravity: 0.7,
        escape_velocity: 1.3,
        rotation_period: -153.3,
        length_of_day: 153.3,
        distance_from_sun: 5906.4,
        pharihelion: 4436.8,
        aphelion: 7375.9,
        orbital_period: 90.560,
        orbital_velocity: 4.7,
        orbital_inclination: 17.2,
        orbital_eccentricity: 0.244,
        obliquity_to_orbit: 122.5,
        mean_temprature: -225.,
        surface_pressure: 0.00001,
        number_of_moons: 5,
        ring_system: false,
        global_magnetic_field: false,
    };
}
